services:
  onlyoffice-documentserver:
    build:
      context: ./
      dockerfile: Dockerfile.external-dependencies
    image: onlyoffice-documentserver-minimal
    container_name: onlyoffice-documentserver
    depends_on:
      onlyoffice-postgresql:
        condition: service_healthy
      onlyoffice-rabbitmq:
        condition: service_healthy
    environment:
      - DB_TYPE=postgres
      - DB_HOST=onlyoffice-postgresql
      - DB_PORT=5432
      - DB_NAME=onlyoffice
      - DB_USER=onlyoffice
      - DB_PWD=onlyoffice
      - AMQP_URI=amqp://guest:guest@onlyoffice-rabbitmq
    ports:
      - '80:80'
    restart: always
    stop_grace_period: 60s
       
  onlyoffice-rabbitmq:
    container_name: onlyoffice-rabbitmq
    image: rabbitmq:3
    restart: always
    expose:
      - '5672'
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 10s

  onlyoffice-postgresql:
    container_name: onlyoffice-postgresql
    image: postgres:15
    environment:
      - POSTGRES_DB=onlyoffice
      - POSTGRES_USER=onlyoffice
      - POSTGRES_PASSWORD=onlyoffice
    restart: always
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U onlyoffice"]
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 10s

volumes:
  postgresql_data: